name: test
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [stable, nightly]
        neo: [true, false]
    env:
      VIM_COMMAND: ${{ matrix.neo && 'nvim' || 'vim' }}
    name: Test against ${{ matrix.neo && 'Neovim' || 'Vim' }} ${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ${{  matrix.neo && 'Neovim' || 'Vim' }} ${{ matrix.version }}
        uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.neo }}

      - name: Setup Just
        uses: extractions/setup-just@v1
        with:
          just-version: 1.14

      - name: Run tests
        run: just test
